name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Check for package.json
      run: |
        if [ ! -f package.json ]; then
          echo "No Node.js project detected. Skipping install, build, and test steps."
          exit 0
        fi
    - name: Install dependencies
      if: hashFiles('package.json') != ''
      run: npm install
    - name: Build (if present)
      if: hashFiles('package.json') != ''
      run: npm run build --if-present
    - name: Test (if present)
      if: hashFiles('package.json') != ''
      run: npm test || echo "No tests found."
